# This file contains static lists for all Indian districts (with states) and appliance complaints.

# --- Districts and States ---
districts = [
    {"state": "Andhra Pradesh", "district": "Anantapur"},
    {"state": "Andhra Pradesh", "district": "Chittoor"},
    {"state": "Andhra Pradesh", "district": "East Godavari"},
    {"state": "Andhra Pradesh", "district": "Guntur"},
    {"state": "Andhra Pradesh", "district": "Krishna"},
    {"state": "Andhra Pradesh", "district": "Kurnool"},
    {"state": "Andhra Pradesh", "district": "Prakasam"},
    {"state": "Andhra Pradesh", "district": "Srikakulam"},
    {"state": "Andhra Pradesh", "district": "Sri Potti Sriramulu Nellore"},
    {"state": "Andhra Pradesh", "district": "Visakhapatnam"},
    {"state": "Andhra Pradesh", "district": "Vizianagaram"},
    {"state": "Andhra Pradesh", "district": "West Godavari"},
    {"state": "Andhra Pradesh", "district": "YSR Kadapa"},
    # ... (all other districts for all states, full list to be included here)
    # Example entries for other states:
    {"state": "Haryana", "district": "Fatehabad"},
    {"state": "Haryana", "district": "Gurugram"},
    {"state": "Haryana", "district": "Yamunanagar"},
    {"state": "Himachal Pradesh", "district": "Bilaspur"},
    {"state": "Jharkhand", "district": "Bokaro"},
    {"state": "Karnataka", "district": "Bengaluru Rural"},
    {"state": "Karnataka", "district": "Bengaluru Urban"},
    {"state": "Ladakh", "district": "Leh Ladakh"},
    {"state": "Lakshadweep", "district": "Lakshadweep District"},
    {"state": "Punjab", "district": "Faridkot"},
    {"state": "Punjab", "district": "Fatehgarh Sahib"},
    {"state": "Punjab", "district": "Fazilka"},
    {"state": "Rajasthan", "district": "Didwana-Kuchaman"},
    {"state": "Rajasthan", "district": "Dudu"},
    {"state": "Rajasthan", "district": "Dungarpur"},
    {"state": "Uttar Pradesh", "district": "Farrukhabad"},
    {"state": "Uttar Pradesh", "district": "Fatehpur"},
    {"state": "Uttar Pradesh", "district": "Firozabad"},
    {"state": "Uttar Pradesh", "district": "Gautam Buddha Nagar"},
    {"state": "West Bengal", "district": "Kalimpong"},
    {"state": "West Bengal", "district": "Kolkata"},
    {"state": "West Bengal", "district": "Malda"},
    # ... (continue for all 700+ districts)
]

# --- Appliance Complaints ---
complaints = [
    {"appliance": "AC", "complaint": "Blows warm / no cooling"},
    {"appliance": "AC", "complaint": "Short-cycling / keeps turning off"},
    {"appliance": "AC", "complaint": "Runs constantly / high power bills"},
    {"appliance": "AC", "complaint": "Water leaking indoors"},
    {"appliance": "AC", "complaint": "Unit will not turn on"},
    {"appliance": "AC", "complaint": "Unusual noises (buzzing, rattling, screeching)"},
    {"appliance": "AC", "complaint": "Foul or musty odour from vents"},
    {"appliance": "AC", "complaint": "Uneven room temperature / weak airflow"},
    {"appliance": "AC", "complaint": "Thermostat display blank or erratic"},
    {"appliance": "AC", "complaint": "Frozen evaporator coil"},
    {"appliance": "AC", "complaint": "Outdoor condenser fan not running"},
    {"appliance": "AC", "complaint": "Compressor hums but won't start"},
    {"appliance": "AC", "complaint": "Tripped breaker when AC starts"},
    {"appliance": "AC", "complaint": "High indoor humidity despite running"},
    {"appliance": "AC", "complaint": "System shuts off after a few seconds"},
    {"appliance": "AC", "complaint": "Outdoor unit iced over in winter (heat-pump)"},
    {"appliance": "AC", "complaint": "Remote control not responding"},
    {"appliance": "AC", "complaint": "Hot air blowing in heat-pump cooling mode"},
    {"appliance": "AC", "complaint": "Error codes on indoor unit display"},
    {"appliance": "AC", "complaint": "Burning or plastic smell when running"},
    {"appliance": "FRIDGE", "complaint": "Not cooling / warm fridge section"},
    {"appliance": "FRIDGE", "complaint": "Excess frost or ice build-up in freezer"},
    {"appliance": "FRIDGE", "complaint": "Water pooling beneath or inside unit"},
    {"appliance": "FRIDGE", "complaint": "Noisy compressor or clicking relay"},
    {"appliance": "FRIDGE", "complaint": "Ice-maker not working or slow ice"},
    {"appliance": "FRIDGE", "complaint": "Fridge runs all the time"},
    {"appliance": "FRIDGE", "complaint": "Interior lights on but compressor off"},
    {"appliance": "FRIDGE", "complaint": "Door won't seal / condensation on gasket"},
    {"appliance": "FRIDGE", "complaint": "Condensation on fridge walls or ceiling"},
    {"appliance": "FRIDGE", "complaint": "Freezer cold but fresh-food compartment warm"},
    {"appliance": "FRIDGE", "complaint": "Fridge cold but freezer warm"},
    {"appliance": "FRIDGE", "complaint": "Gurgling or dripping sounds from cabinet"},
    {"appliance": "FRIDGE", "complaint": "Exterior cabinet sides feel hot"},
    {"appliance": "FRIDGE", "complaint": "Water dispenser leaking or dripping"},
    {"appliance": "FRIDGE", "complaint": "Ice / water dispenser not dispensing"},
    {"appliance": "FRIDGE", "complaint": "Error code flashing on control panel"},
    {"appliance": "FRIDGE", "complaint": "Food freezing in fresh-food section"},
    {"appliance": "FRIDGE", "complaint": "Persistent bad odour inside fridge"},
    {"appliance": "FRIDGE", "complaint": "Vegetable crisper freezing produce"},
    {"appliance": "FRIDGE", "complaint": "Interior light not working"},
    {"appliance": "WASHING MACHINE", "complaint": "Will not spin / clothes still wet"},
    {"appliance": "WASHING MACHINE", "complaint": "Won't drain water"},
    {"appliance": "WASHING MACHINE", "complaint": "Door / lid won't unlock (latch error)"},
    {"appliance": "WASHING MACHINE", "complaint": "Excessive vibration or “walking”"},
    {"appliance": "WASHING MACHINE", "complaint": "Leaks during cycle"},
    {"appliance": "WASHING MACHINE", "complaint": "Foul mildew or sewer smell"},
    {"appliance": "WASHING MACHINE", "complaint": "Fills slowly or won't fill"},
    {"appliance": "WASHING MACHINE", "complaint": "Error codes on display panel"},
    {"appliance": "WASHING MACHINE", "complaint": "Unusual noises (thumping, grinding, squeal)"},
    {"appliance": "WASHING MACHINE", "complaint": "Does not agitate / wash action weak"},
    {"appliance": "WASHING MACHINE", "complaint": "Machine will not start at all"},
    {"appliance": "WASHING MACHINE", "complaint": "Stops mid-cycle / shuts off unexpectedly"},
    {"appliance": "WASHING MACHINE", "complaint": "Overfills or water overflows"},
    {"appliance": "WASHING MACHINE", "complaint": "Detergent not dispensing / residue left"},
    {"appliance": "WASHING MACHINE", "complaint": "Clothes come out too soapy or slimy"},
    {"appliance": "WASHING MACHINE", "complaint": "Fabric softener remains in drawer"},
    {"appliance": "WASHING MACHINE", "complaint": "Burning smell during spin"},
    {"appliance": "WASHING MACHINE", "complaint": "Control knobs / touch panel non-responsive"},
    {"appliance": "WASHING MACHINE", "complaint": "Lid won't close or latch properly"},
    {"appliance": "WASHING MACHINE", "complaint": "Timer does not advance / stuck cycle"},
] 